# Period definitions for the unified analytics engine
periods:
  all_year:
    months: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
  heating_season:
    months: [11, 12, 1, 2, 3]
  non_heating_season:
    months: [4, 5, 6, 7, 8, 9, 10]

# Filter definitions
filters:
  opening_hours:
    hours: [8, 9, 10, 11, 12, 13, 14, 15]  # 8 AM to 4 PM
    weekdays_only: true
    exclude_holidays: true
  all_hours:
    hours: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]
    weekdays_only: false
    exclude_holidays: false

# Danish School Holiday Configuration
holidays:
  country: "DK"
  custom_holidays:
    # Summer holidays
    - name: "Summer Holiday Start"
      start_date: "2024-06-22"
      end_date: "2024-08-12"
    # Autumn holidays
    - name: "Autumn Holiday"
      start_date: "2024-10-14"
      end_date: "2024-10-18"
    # Christmas holidays
    - name: "Christmas Holiday Start"
      start_date: "2024-12-21"
      end_date: "2025-01-06"
    # Winter holidays
    - name: "Winter Holiday"
      start_date: "2024-02-12"
      end_date: "2024-02-16"
    # Easter holidays
    - name: "Easter Holiday"
      start_date: "2024-03-25"
      end_date: "2024-04-01"

# Analytics rules based on EN16798-1 structure above
analytics:
  # Temperature rules - Heating Season
  en16798_cat_i_temp_opening_hours:
    feature: temperature
    filter: opening_hours
    period: heating_season
    mode: bidirectional
    limits:
      lower: 21
      upper: 23
    category: EN16798-1
    description: "Temperature Category I compliance during heating season (opening hours)"

  en16798_cat_ii_temp_opening_hours:
    feature: temperature
    filter: opening_hours
    period: heating_season
    mode: bidirectional
    limits:
      lower: 20
      upper: 24
    category: EN16798-1
    description: "Temperature Category II compliance during heating season (opening hours)"

  en16798_cat_iii_temp_opening_hours:
    feature: temperature
    filter: opening_hours
    period: heating_season
    mode: bidirectional
    limits:
      lower: 19
      upper: 25
    category: EN16798-1
    description: "Temperature Category III compliance during heating season (opening hours)"

  # Temperature rules - Non-Heating Season
  en16798_temp_cat_i_opening_hours:
    feature: temperature
    filter: opening_hours
    period: non_heating_season
    mode: bidirectional
    limits:
      lower: 23
      upper: 25
    category: EN16798-1
    description: "Temperature Category I compliance during non-heating season (opening hours)"

  en16798_temp_cat_ii_opening_hours:
    feature: temperature
    filter: opening_hours
    period: non_heating_season
    mode: bidirectional
    limits:
      lower: 22
      upper: 26
    category: EN16798-1
    description: "Temperature Category II compliance during non-heating season (opening hours)"

  en16798_temp_cat_iii_opening_hours:
    feature: temperature
    filter: opening_hours
    period: non_heating_season
    mode: bidirectional
    limits:
      lower: 21
      upper: 27
    category: EN16798-1
    description: "Temperature Category III compliance during non-heating season (opening hours)"

  # Humidity rules
  en16798_cat_i_humidity_opening_hours:
    feature: humidity
    filter: opening_hours
    period: all_year
    mode: bidirectional
    limits:
      lower: 30
      upper: 50
    category: EN16798-1
    description: "Humidity Category I compliance (opening hours)"

  en16798_cat_ii_humidity_opening_hours:
    feature: humidity
    filter: opening_hours
    period: all_year
    mode: bidirectional
    limits:
      lower: 25
      upper: 60
    category: EN16798-1
    description: "Humidity Category II compliance (opening hours)"

  en16798_cat_iii_humidity_opening_hours:
    feature: humidity
    filter: opening_hours
    period: all_year
    mode: bidirectional
    limits:
      lower: 20
      upper: 70
    category: EN16798-1
    description: "Humidity Category III compliance (opening hours)"

  # CO2 rules
  en16798_cat_i_co2_opening_hours:
    feature: co2
    filter: opening_hours
    period: all_year
    mode: unidirectional_ascending
    limit: 550
    category: EN16798-1
    description: "CO2 Category I compliance (opening hours)"

  en16798_cat_ii_co2_opening_hours:
    feature: co2
    filter: opening_hours
    period: all_year
    mode: unidirectional_ascending
    limit: 800
    category: EN16798-1
    description: "CO2 Category II compliance (opening hours)"

  en16798_cat_iii_co2_opening_hours:
    feature: co2
    filter: opening_hours
    period: all_year
    mode: unidirectional_ascending
    limit: 1200
    category: EN16798-1
    description: "CO2 Category III compliance (opening hours)"

  # Additional seasonal temperature rules
  en16798_temp_cat_ii_heating_season:
    feature: temperature
    filter: opening_hours
    period: heating_season
    mode: bidirectional
    limits:
      lower: 20
      upper: 24
    category: EN16798-1
    description: "Temperature Category II compliance during heating season"

  en16798_temp_cat_ii_non_heating_season:
    feature: temperature
    filter: opening_hours
    period: non_heating_season
    mode: bidirectional
    limits:
      lower: 22
      upper: 26
    category: EN16798-1
    description: "Temperature Category II compliance during non-heating season"

  # Danish school guidelines
  temp_comfort_danish_schools:
    feature: temperature
    filter: opening_hours
    period: all_year
    mode: bidirectional
    limits:
      lower: 20
      upper: 26
    category: Danish Guidelines
    description: "Danish school temperature comfort guidelines"

  co2_danish_guidelines:
    feature: co2
    filter: opening_hours
    period: all_year
    mode: unidirectional_ascending
    limit: 1000
    category: Danish Guidelines
    description: "Danish school CO2 guidelines"