analytics:
  temp_below_20_all_year_opening:
    description: Temperature <20°C - Undercooling (all year, opening hours)
    feature: temperature
    period: all_year
    filter: opening_hours
    mode: unidirectional_descending
    limit: 20
  temp_below_20_winter_opening:
    description: Temperature <20°C - Undercooling (winter, opening hours)
    feature: temperature
    period: winter
    filter: opening_hours
    mode: unidirectional_descending
    limit: 20
  temp_above_26_all_year_opening:
    description: Temperature >26°C - Overheating (all year, opening hours)
    feature: temperature
    period: all_year
    filter: opening_hours
    mode: unidirectional_ascending
    limit: 26
  temp_above_26_summer_opening:
    description: Temperature >26°C - Overheating (summer, opening hours)
    feature: temperature
    period: summer
    filter: opening_hours
    mode: unidirectional_ascending
    limit: 26
  temp_above_27_all_year_opening:
    description: Temperature >27°C - Critical overheating (all year, opening hours)
    feature: temperature
    period: all_year
    filter: opening_hours
    mode: unidirectional_ascending
    limit: 27
  temp_above_27_summer_opening:
    description: Temperature >27°C - Critical overheating (summer, opening hours)
    feature: temperature
    period: summer
    filter: opening_hours
    mode: unidirectional_ascending
    limit: 27
  temp_above_28_all_year_all_hours:
    description: Temperature >28°C - Extreme overheating (all year, all hours)
    feature: temperature
    period: all_year
    filter: all_hours
    mode: unidirectional_ascending
    limit: 28
  # BR18 Danish Building Regulations - Office Buildings
  br18_office_temp_above_26_max_100h:
    description: BR18 Office - Max 100h/year >26°C (all hours during usage time)
    feature: temperature
    period: all_year
    filter: opening_hours
    mode: unidirectional_ascending
    limit: 26
    max_exceedance_hours: 100
    regulation: BR18
    building_type: office
  br18_office_temp_above_27_max_25h:
    description: BR18 Office - Max 25h/year >27°C (all hours during usage time)
    feature: temperature
    period: all_year
    filter: opening_hours
    mode: unidirectional_ascending
    limit: 27
    max_exceedance_hours: 25
    regulation: BR18
    building_type: office
  # BR18 Danish Building Regulations - Residential with Natural Ventilation
  br18_residential_temp_above_27_max_100h:
    description: BR18 Residential - Max 100h/year >27°C (natural ventilation, all hours)
    feature: temperature
    period: all_year
    filter: all_hours
    mode: unidirectional_ascending
    limit: 27
    max_exceedance_hours: 100
    regulation: BR18
    building_type: residential
    ventilation_type: natural
  br18_residential_temp_above_28_max_25h:
    description: BR18 Residential - Max 25h/year >28°C (natural ventilation, all hours)
    feature: temperature
    period: all_year
    filter: all_hours
    mode: unidirectional_ascending
    limit: 28
    max_exceedance_hours: 25
    regulation: BR18
    building_type: residential
    ventilation_type: natural
  temp_comfort_zone_20_26_all_year_opening:
    description: Temperature 20-26°C - Comfort zone (all year, opening hours, excl. holidays)
    feature: temperature
    period: all_year
    filter: opening_hours_no_holidays
    mode: bidirectional
    limits:
      upper: 26
      lower: 20
  temp_comfort_zone_20_26_spring_opening:
    description: Temperature 20-26°C - Comfort zone (spring, opening hours, excl. holidays)
    feature: temperature
    period: spring
    filter: opening_hours_no_holidays
    mode: bidirectional
    limits:
      upper: 26
      lower: 20
  temp_comfort_zone_20_26_summer_opening:
    description: Temperature 20-26°C - Comfort zone (summer, opening hours, excl. holidays)
    feature: temperature
    period: summer
    filter: opening_hours_no_holidays
    mode: bidirectional
    limits:
      upper: 26
      lower: 20
  temp_comfort_zone_20_26_autumn_opening:
    description: Temperature 20-26°C - Comfort zone (autumn, opening hours, excl. holidays)
    feature: temperature
    period: autumn
    filter: opening_hours_no_holidays
    mode: bidirectional
    limits:
      upper: 26
      lower: 20
  temp_comfort_zone_20_26_winter_opening:
    description: Temperature 20-26°C - Comfort zone (winter, opening hours, excl. holidays)
    feature: temperature
    period: winter
    filter: opening_hours_no_holidays
    mode: bidirectional
    limits:
      upper: 26
      lower: 20
  temp_optimal_zone_21_24_all_year_opening:
    description: Temperature 21-24°C - Optimal comfort (all year, opening hours, excl. holidays)
    feature: temperature
    period: all_year
    filter: opening_hours_no_holidays
    mode: bidirectional
    limits:
      upper: 24
      lower: 21
  co2_1000_all_year_opening:
    description: CO₂ <1000ppm - Standard air quality (all year, opening hours, excl. holidays)
    feature: co2
    period: all_year
    filter: opening_hours_no_holidays
    mode: unidirectional_ascending
    limit: 1000
  co2_1000_all_year_non_opening:
    description: CO₂ <1000ppm - Standard air quality (all year, outside opening hours)
    feature: co2
    period: all_year
    filter: non_opening_hours
    mode: unidirectional_ascending
    limit: 1000
  co2_1000_spring_opening:
    description: CO₂ <1000ppm - Standard air quality (spring, opening hours, excl. holidays)
    feature: co2
    period: spring
    filter: opening_hours_no_holidays
    mode: unidirectional_ascending
    limit: 1000
  co2_1000_summer_opening:
    description: CO₂ <1000ppm - Standard air quality (summer, opening hours, excl. holidays)
    feature: co2
    period: summer
    filter: opening_hours_no_holidays
    mode: unidirectional_ascending
    limit: 1000
  co2_1000_autumn_opening:
    description: CO₂ <1000ppm - Standard air quality (autumn, opening hours, excl. holidays)
    feature: co2
    period: autumn
    filter: opening_hours_no_holidays
    mode: unidirectional_ascending
    limit: 1000
  co2_1000_winter_opening:
    description: CO₂ <1000ppm - Standard air quality (winter, opening hours, excl. holidays)
    feature: co2
    period: winter
    filter: opening_hours_no_holidays
    mode: unidirectional_ascending
    limit: 1000
  co2_2000_all_year_opening:
    description: CO₂ <2000ppm - Acceptable threshold (all year, opening hours, excl. holidays)
    feature: co2
    period: all_year
    filter: opening_hours_no_holidays
    mode: unidirectional_ascending
    limit: 2000
  co2_2000_all_year_non_opening:
    description: CO₂ <2000ppm - Acceptable threshold (all year, outside opening hours)
    feature: co2
    period: all_year
    filter: non_opening_hours
    mode: unidirectional_ascending
    limit: 2000
  co2_2000_spring_opening:
    description: CO₂ <2000ppm - Acceptable threshold (spring, opening hours, excl. holidays)
    feature: co2
    period: spring
    filter: opening_hours_no_holidays
    mode: unidirectional_ascending
    limit: 2000
  co2_2000_summer_opening:
    description: CO₂ <2000ppm - Acceptable threshold (summer, opening hours, excl. holidays)
    feature: co2
    period: summer
    filter: opening_hours_no_holidays
    mode: unidirectional_ascending
    limit: 2000
  co2_2000_autumn_opening:
    description: CO₂ <2000ppm - Acceptable threshold (autumn, opening hours, excl. holidays)
    feature: co2
    period: autumn
    filter: opening_hours_no_holidays
    mode: unidirectional_ascending
    limit: 2000
  co2_2000_winter_opening:
    description: CO₂ <2000ppm - Acceptable threshold (winter, opening hours, excl. holidays)
    feature: co2
    period: winter
    filter: opening_hours_no_holidays
    mode: unidirectional_ascending
    limit: 2000
  co2_1000_morning:
    description: CO₂ <1000ppm (morning 8-11, opening hours, excl. holidays)
    feature: co2
    period: all_year
    filter: morning_no_holidays
    mode: unidirectional_ascending
    limit: 1000
  co2_1000_afternoon:
    description: CO₂ <1000ppm (afternoon 12-15, opening hours, excl. holidays)
    feature: co2
    period: all_year
    filter: afternoon_no_holidays
    mode: unidirectional_ascending
    limit: 1000
  co2_1000_evening_opening:
    description: CO₂ <1000ppm (evening 16-21, opening hours, excl. holidays)
    feature: co2
    period: all_year
    filter: evening_no_holidays
    mode: unidirectional_ascending
    limit: 1000
  co2_2000_morning_opening:
    description: CO₂ <2000ppm (morning 8-11, opening hours, excl. holidays)
    feature: co2
    period: all_year
    filter: morning_no_holidays
    mode: unidirectional_ascending
    limit: 2000
  co2_2000_afternoon_opening:
    description: CO₂ <2000ppm (afternoon 12-15, opening hours, excl. holidays)
    feature: co2
    period: all_year
    filter: afternoon_no_holidays
    mode: unidirectional_ascending
    limit: 2000
  co2_2000_evening_opening:
    description: CO₂ <2000ppm (evening 16-21, opening hours, excl. holidays)
    feature: co2
    period: all_year
    filter: evening_no_holidays
    mode: unidirectional_ascending
    limit: 2000
  temp_comfort_zone_20_26_morning_opening:
    description: Temperature 20-26°C - Comfort zone (morning 8-11, opening hours, excl. holidays)
    feature: temperature
    period: all_year
    filter: morning_no_holidays
    mode: bidirectional
    limits:
      upper: 26
      lower: 20
  temp_comfort_zone_20_26_afternoon_opening:
    description: Temperature 20-26°C - Comfort zone (afternoon 12-15, opening hours, excl. holidays)
    feature: temperature
    period: all_year
    filter: afternoon_no_holidays
    mode: bidirectional
    limits:
      upper: 26
      lower: 20
  temp_comfort_zone_20_26_evening_opening:
    description: Temperature 20-26°C - Comfort zone (evening 16-21, opening hours, excl. holidays)
    feature: temperature
    period: all_year
    filter: evening_no_holidays
    mode: bidirectional
    limits:
      upper: 26
      lower: 20
  comfort_optimal_opening:
    description: Optimal comfort (temperature 21-24°C and CO2 <800ppm, opening hours)
    feature: combined
    period: all_year
    filter: opening_hours
    json_logic:
      and:
      - and:
        - '>=':
          - var: temperature
          - 21
        - <=:
          - var: temperature
          - 24
      - <:
        - var: co2
        - 1000
  temp_between_20-26:
    description: Temperature between 20 and 26 degrees C
    feature: temperature
    period: all_year
    filter: opening_hours
    mode: bidirectional
    limits:
      upper: 26.0
      lower: 20.0
periods:
  all_year:
    months:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
  spring:
    months:
    - 3
    - 4
    - 5
  summer:
    months:
    - 6
    - 7
    - 8
  autumn:
    months:
    - 9
    - 10
    - 11
  winter:
    months:
    - 12
    - 1
    - 2
  heating_season:
    months:
    - 11
    - 12
    - 1
    - 2
    - 3
  non_heating_season:
    months:
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
filters:
  opening_hours:
    hours:
    - 8
    - 9
    - 10
    - 11
    - 12
    - 13
    - 14
    - 15
    weekdays_only: true
    exclude_holidays: true
  opening_hours_no_holidays:
    description: Opening hours (8-15), weekdays, excludes all school holidays
    hours:
    - 8
    - 9
    - 10
    - 11
    - 12
    - 13
    - 14
    - 15
    weekdays_only: true
    exclude_holidays: true
    exclude_custom_holidays: true
  non_opening_hours:
    hours:
    - 16
    - 17
    - 18
    - 19
    - 20
    - 21
    - 22
    - 23
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    weekdays_only: false
    exclude_holidays: false
  morning:
    hours:
    - 8
    - 9
    - 10
    - 11
    weekdays_only: false
    exclude_holidays: false
  morning_no_holidays:
    description: Morning (8-11), weekdays, excludes school holidays
    hours:
    - 8
    - 9
    - 10
    - 11
    weekdays_only: true
    exclude_holidays: true
    exclude_custom_holidays: true
  afternoon:
    hours:
    - 12
    - 13
    - 14
    - 15
    weekdays_only: false
    exclude_holidays: false
  afternoon_no_holidays:
    description: Afternoon (12-15), weekdays, excludes school holidays
    hours:
    - 12
    - 13
    - 14
    - 15
    weekdays_only: true
    exclude_holidays: true
    exclude_custom_holidays: true
  evening:
    hours:
    - 16
    - 17
    - 18
    - 19
    - 20
    - 21
    weekdays_only: false
    exclude_holidays: false
  evening_no_holidays:
    description: Evening (16-21), weekdays, excludes school holidays
    hours:
    - 16
    - 17
    - 18
    - 19
    - 20
    - 21
    weekdays_only: true
    exclude_holidays: true
    exclude_custom_holidays: true
  night:
    hours:
    - 22
    - 23
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    weekdays_only: false
    exclude_holidays: false
  all_hours:
    hours:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
    - 13
    - 14
    - 15
    - 16
    - 17
    - 18
    - 19
    - 20
    - 21
    - 22
    - 23
    weekdays_only: false
    exclude_holidays: false
holidays:
  country: DK
  custom_holidays:
  - name: Summer Holiday Start
    start_date: '2024-06-29'
    end_date: '2024-08-11'
  - name: Autumn Holiday
    start_date: '2024-10-12'
    end_date: '2024-10-20'
  - name: Christmas Holiday Start
    start_date: '2024-12-21'
    end_date: '2025-01-03'
  - name: Winter Holiday
    start_date: '2024-02-17'
    end_date: '2024-02-25'
  - name: Easter Holiday
    start_date: '2024-03-23'
    end_date: '2024-04-01'
table_mappings:
  daily_periods_table:
    description: Maps day period tests to table fields
    periods:
      morning:
        display_name: Morning (08-12)
        co2_1000_compliance: co2_1000_morning
        co2_2000_compliance: co2_2000_morning_opening
        temp_compliance: temp_comfort_zone_20_26_morning_opening
        avg_co2: Extracted from mean values of co2_1000_morning
        avg_temp: Extracted from mean values of temp_comfort_zone_20_26_morning_opening
      afternoon:
        display_name: Afternoon (12-16)
        co2_1000_compliance: co2_1000_afternoon
        co2_2000_compliance: co2_2000_afternoon_opening
        temp_compliance: temp_comfort_zone_20_26_afternoon_opening
        avg_co2: Extracted from mean values of co2_1000_afternoon
        avg_temp: Extracted from mean values of temp_comfort_zone_20_26_afternoon_opening
      evening:
        display_name: Evening (16-21)
        co2_1000_compliance: co2_1000_evening_opening
        co2_2000_compliance: co2_2000_evening_opening
        temp_compliance: temp_comfort_zone_20_26_evening_opening
        avg_co2: Extracted from mean values of co2_1000_evening_opening
        avg_temp: Extracted from mean values of temp_comfort_zone_20_26_evening_opening
  seasonal_table:
    description: Maps seasonal tests to table fields
    seasons:
      spring:
        display_name: Spring
        co2_1000_compliance: co2_1000_spring_opening
        co2_2000_compliance: co2_2000_spring_opening
        temp_compliance: temp_comfort_zone_20_26_spring_opening
        avg_co2: Extracted from mean values of co2_1000_spring_opening
        avg_temp: Extracted from mean values of temp_comfort_zone_20_26_spring_opening
      summer:
        display_name: Summer
        co2_1000_compliance: co2_1000_summer_opening
        co2_2000_compliance: co2_2000_summer_opening
        temp_compliance: temp_comfort_zone_20_26_summer_opening
        avg_co2: Extracted from mean values of co2_1000_summer_opening
        avg_temp: Extracted from mean values of temp_comfort_zone_20_26_summer_opening
      autumn:
        display_name: Autumn
        co2_1000_compliance: co2_1000_autumn_opening
        co2_2000_compliance: co2_2000_autumn_opening
        temp_compliance: temp_comfort_zone_20_26_autumn_opening
        avg_co2: Extracted from mean values of co2_1000_autumn_opening
        avg_temp: Extracted from mean values of temp_comfort_zone_20_26_autumn_opening
      winter:
        display_name: Winter
        co2_1000_compliance: co2_1000_winter_opening
        co2_2000_compliance: co2_2000_winter_opening
        temp_compliance: temp_comfort_zone_20_26_winter_opening
        avg_co2: Extracted from mean values of co2_1000_winter_opening
        avg_temp: Extracted from mean values of temp_comfort_zone_20_26_winter_opening
