# Default TAIL Rating Scheme Configuration
# Base configuration that applies to all building and room types unless overridden

tail_config:
  version: "1.0"
  description: "Default TAIL (Thermal, Acoustics, Indoor Air Quality, Lighting) Rating Scheme Configuration"
  
  # Default parameter configurations (applied to all unless overridden)
  default_parameters:
    # Temperature - seasonal frequency-based analysis
    temperature:
      calculation_method: "seasonal_frequency"
      heating_season:
        months: [10, 11, 12, 1, 2, 3, 4, 5]
        thresholds:
          green:
            min: 21
            max: 23
          yellow:
            conditions: ["20-21", "23-24"]
          orange:
            conditions: ["19-20", "24-25"]
          red:
            condition: "<19 or >25"
      non_heating_season:
        months: [6, 7, 8, 9]
        thresholds:
          green:
            min: 23.5
            max: 25.5
          yellow:
            conditions: ["23-23.5", "25.5-26"]
          orange:
            conditions: ["22-23", "26-27"]
          red:
            condition: "<22 or >27"
    
    # CO2 - universal WHO/EN16798 based (95th percentile)
    co2:
      calculation_method: "percentile"
      percentile: 95
      thresholds:
        green:
          max: 970
        yellow:
          min: 970
          max: 1220
        orange:
          min: 1220
          max: 1770
        red:
          min: 1770
    
    # Relative Humidity - default frequency-based analysis
    humidity:
      calculation_method: "frequency_based"
      thresholds:
        green:
          min: 30
          max: 50
        yellow:
          conditions: ["25-30", "50-60"]
        orange:
          conditions: ["20-25", "60-70"]
        red:
          condition: "<20 or >70"
    
    # PM2.5 - WHO health-based limits
    pm25:
      calculation_method: "direct"
      thresholds:
        green:
          max: 10
        yellow:
          min: 10
          max: 25
        red:
          min: 25
    
    # Formaldehyde - WHO health-based limits
    formaldehyde:
      calculation_method: "direct"
      thresholds:
        green:
          max: 30
        yellow:
          min: 30
          max: 100
        red:
          min: 100
    
    # Benzene - WHO health-based limits
    benzene:
      calculation_method: "direct"
      thresholds:
        green:
          max: 2
        yellow:
          min: 2
          max: 5
        red:
          min: 5
    
    # Radon - WHO health-based limits
    radon:
      calculation_method: "direct"
      thresholds:
        green:
          max: 100
        yellow:
          min: 100
          max: 300
        red:
          min: 300
    
    # Ventilation - occupancy and floor area based
    ventilation:
      calculation_method: "occupancy_based"
      formulas:
        green: "10 * occupancy + 2 * floor_area"
        yellow: "7 * occupancy + 1.4 * floor_area"
        orange: "4 * occupancy + 0.8 * floor_area"
    
    # Noise - default thresholds (5th percentile)
    noise:
      calculation_method: "percentile"
      percentile: 5
      thresholds:
        green:
          max: 35
        yellow:
          min: 35
          max: 40
        orange:
          min: 40
          max: 45
        red:
          min: 45
    
    # Illuminance - default frequency-based analysis
    illuminance:
      calculation_method: "frequency_range"
      target_range:
        min: 300
        max: 500
      thresholds:
        green:
          frequency_percentage: 60
        yellow:
          frequency_percentage: 40
        orange:
          frequency_percentage: 10
        red:
          frequency_percentage: 0
    
    # Daylight Factor - direct value assessment
    daylight_factor:
      calculation_method: "direct"
      thresholds:
        green:
          min: 5.0
        yellow:
          min: 3.3
          max: 5.0
        orange:
          min: 2.0
          max: 3.3
        red:
          max: 2.0
    
    # Mold - categorical visual inspection
    mold:
      calculation_method: "categorical"
      categories:
        green: "No visible mold"
        yellow: "Small areas visible mold, <400 cm2"
        orange: "Slightly larger areas visible mold, < 2500 cm2"
        red: "Large areas visible mold, > 2500 cm2"