graphs:
  - id: temperature_timeseries
    name: Temperature Time Series
    description: Time series plot of temperature readings over time
    category: environmental
    type: line_chart
    fixture: sample_temperature.json
    parameters:
      - name: moving_average
        type: number
        default: 24
        description: Moving average window in hours
      - name: show_targets
        type: boolean
        default: true
        description: Show target temperature bands

  - id: room_temperature_co2
    name: Temperature and CO2 Trends
    description: Time series showing temperature and CO2 over time
    category: environmental
    type: line_chart
    fixture: sample_room_timeseries.json
    parameters:
      - name: metrics
        type: list
        default: ["temperature", "co2"]
        description: Metrics to plot
      - name: time_periods
        type: list
        default: ["all_year", "opening_hours", "non_opening_hours"]
        description: Time periods to display
      - name: co2_thresholds
        type: list
        default: [1000, 2000]
        description: CO2 threshold lines
      - name: temp_thresholds
        type: list
        default: [20, 26]
        description: Temperature threshold lines

  - id: seasonal_analysis
    name: Seasonal Performance Analysis
    description: Box plots showing seasonal variations in metrics
    category: environmental
    type: line_chart
    fixture: sample_seasonal_patterns.json
    parameters:
      - name: seasons
        type: list
        default: ["spring", "summer", "autumn", "winter"]
        description: Seasons to analyze
      - name: metrics
        type: list
        default: ["temperature", "co2"]
        description: Metrics to analyze
      - name: chart_type
        type: string
        default: box_plot
        description: Visualization type

  - id: daily_patterns
    name: Daily Distribution Patterns
    description: Line chart with bounds showing daily patterns
    category: environmental
    type: line_chart
    fixture: sample_daily_distribution.json
    parameters:
      - name: time_resolution
        type: string
        default: hour
        description: Time resolution
      - name: metrics
        type: list
        default: ["temperature", "co2"]
        description: Metrics to display
      - name: show_bounds
        type: boolean
        default: true
        description: Show upper and lower bounds
      - name: chart_type
        type: string
        default: line_with_bounds
        description: Chart type

  - id: yearly_trends
    name: Yearly Trends
    description: Temperature and CO2 trends over the year with moving averages
    category: environmental
    type: line_chart
    fixture: sample_yearly_trends.json
    parameters:
      - name: metrics
        type: list
        default: ["temperature", "co2"]
        description: Metrics to plot
      - name: moving_average_window
        type: number
        default: 168
        description: Moving average window in hours (default 7 days)

  - id: temperature_heatmap
    name: Temperature Heatmap
    description: Hour-of-day vs day-of-week temperature heatmap
    category: environmental
    type: heatmap
    fixture: sample_temperature_heatmap.json
    parameters:
      - name: color_scheme
        type: string
        default: RdYlBu_r
        description: Color scheme for heatmap

  - id: co2_heatmap
    name: CO2 Heatmap
    description: Hour-of-day vs day-of-week CO2 concentration heatmap
    category: environmental
    type: heatmap
    fixture: sample_co2_heatmap.json
    parameters:
      - name: color_scheme
        type: string
        default: YlOrRd
        description: Color scheme for heatmap
      - name: threshold
        type: number
        default: 1000
        description: CO2 threshold line

  - id: climate_correlation_heatmap
    name: Climate Correlation Heatmap
    description: Correlation heatmap between indoor and outdoor climate
    category: environmental
    type: heatmap
    fixture: sample_climate_correlation.json
    parameters:
      - name: variables
        type: list
        default: ["indoor_temp", "outdoor_temp", "co2", "humidity", "solar_radiation"]
        description: Variables to correlate

  - id: solar_sensitivity_chart
    name: Solar Sensitivity Chart
    description: Temperature vs solar radiation scatter plot
    category: environmental
    type: line_chart
    fixture: sample_solar_sensitivity.json
    parameters:
      - name: color_by
        type: string
        default: season
        description: Color points by season or time

  - id: seasonal_climate_correlation
    name: Seasonal Climate Correlation
    description: Seasonal breakdown of indoor-outdoor temperature correlation
    category: environmental
    type: line_chart
    fixture: sample_seasonal_climate.json
    parameters:
      - name: seasons
        type: list
        default: ["spring", "summer", "autumn", "winter"]
        description: Seasons to analyze
