# Building KPI Report Template
# Building-level KPIs only - executive summary

template_name: "building_kpi_report"
report_type: "building"
title: "Building Performance - Executive KPI Report"
description: "High-level overview of building IEQ performance with key metrics only"
author: "IEQ Analytics Platform"

# Room filtering - all rooms for aggregation but not shown individually
room_filter:
  mode: "all"
  sort_by: "compliance"
  ascending: false

# Report sections - KPIs only, no room details
sections:
  # Executive summary
  - type: "executive_summary"
    title: "Executive Summary"
    description: "Quick overview of building performance"

  # Building KPI dashboard with gauges
  - type: "chart"
    title: "Key Performance Indicators"
    description: "Building-level compliance, quality, and violation metrics"
    chart:
      type: "building_kpi_dashboard"

  # Building comparison (if multiple buildings)
  - type: "chart"
    title: "Performance Trends"
    description: "Overall compliance rate trends"
    chart:
      type: "bar_building_comparison"
      sort: true

  # Compliance gauge
  - type: "chart"
    title: "Overall Compliance Rate"
    description: "Building-wide compliance gauge"
    chart:
      type: "compliance_gauge"

  # Top recommendations only
  - type: "recommendations"
    title: "Strategic Recommendations"
    description: "Top priority actions for building management"
    max_recommendations: 5

# Output settings
output_format: ["html"]
include_interactive_charts: true
theme: "professional"

# Compliance settings
compliance_standard: "EN16798-1"
building_class: "II"
