# Problematic Rooms Report Template
# Shows only failing rooms with detailed violation analysis

template_name: "problematic_rooms_report"
report_type: "building"
title: "Problematic Rooms - IEQ Compliance Report"
description: "Focused analysis of rooms failing to meet compliance standards"
author: "IEQ Analytics Platform"

# Room filtering - show only failing rooms
room_filter:
  mode: "failing"  # Only rooms below threshold
  compliance_threshold: 95.0  # Rooms below 95% compliance
  sort_by: "compliance"  # Sort by compliance (worst first)
  ascending: true  # Worst performers first

# Report sections
sections:
  # Summary of problematic rooms
  - type: "summary"
    title: "Problematic Rooms Summary"
    description: "Overview of rooms requiring immediate attention"

  # Bar chart showing only failing rooms
  - type: "chart"
    title: "Failing Rooms - Compliance Rates"
    description: "Rooms below 95% compliance threshold"
    chart:
      type: "bar_room_comparison"
      metric: "compliance"
      sort: true
      ascending: true  # Worst first
      show_only_failing: true
      failing_threshold: 95.0

  # Violation timeline for worst performing rooms
  - type: "chart"
    title: "Violation Timeline - Critical Periods"
    description: "When and how severe were the violations"
    chart:
      type: "violation_timeline"
      parameters: ["temperature"]

  # Temperature compliance timeseries with RED highlighting
  - type: "chart"
    title: "Temperature Violations - Detailed View"
    description: "Non-compliant periods highlighted in RED"
    chart:
      type: "timeseries_compliance"
      parameters: ["temperature"]
      season: "winter"  # Focus on most problematic season
      show_threshold: true

  # CO2 violations
  - type: "chart"
    title: "CO2 Violations - Detailed View"
    description: "Non-compliant periods highlighted in RED"
    chart:
      type: "timeseries_compliance"
      parameters: ["co2"]
      season: "all"
      show_threshold: true

  # Compliance heatmap - identify problem hours
  - type: "chart"
    title: "When Do Violations Occur?"
    description: "Compliance patterns by hour and day"
    chart:
      type: "heatmap_compliance"
      parameters: ["temperature"]
      season: "winter"

  # Detailed table with failing rooms only
  - type: "table"
    title: "Failing Rooms - Detailed Metrics"
    description: "Complete breakdown for rooms requiring attention"

  # High priority recommendations
  - type: "recommendations"
    title: "Urgent Improvement Actions"
    description: "High-priority recommendations to address compliance failures"
    max_recommendations: 15

# Output settings
output_format: ["html"]
include_interactive_charts: true
theme: "professional"

# Compliance settings
compliance_standard: "EN16798-1"
building_class: "II"
