# Top and Bottom Performers Report Template
# Shows only the best and worst performing rooms

template_name: "top_bottom_performers_report"
report_type: "building"
title: "Best and Worst Performing Rooms - IEQ Analysis"
description: "Comparative analysis of top and bottom performing rooms to identify success factors and problem areas"
author: "IEQ Analytics Platform"

# This template will be generated twice:
# 1. Once with top_n for best performers
# 2. Once with bottom_n for worst performers

# Room filtering - top 10 performers
room_filter:
  mode: "top_n"  # Can be changed to "bottom_n" for worst performers
  n: 10  # Number of rooms to show
  compliance_threshold: 95.0
  sort_by: "compliance"
  ascending: false  # Best first for top_n, set to true for bottom_n

# Report sections
sections:
  # Summary
  - type: "summary"
    title: "Performance Summary"
    description: "Overview of selected rooms"

  # Comparison bar chart
  - type: "chart"
    title: "Compliance Comparison - Top/Bottom Performers"
    description: "Side-by-side comparison of compliance rates"
    chart:
      type: "bar_room_comparison"
      metric: "compliance"
      sort: true
      ascending: false  # Match room_filter setting
      show_only_failing: false

  # Violations comparison
  - type: "chart"
    title: "Violation Counts - Comparison"
    description: "Number of violations across selected rooms"
    chart:
      type: "bar_room_comparison"
      metric: "violations"
      sort: true
      ascending: true  # Fewer violations is better

  # Quality comparison
  - type: "chart"
    title: "Data Quality - Comparison"
    description: "Data quality scores for selected rooms"
    chart:
      type: "bar_room_comparison"
      metric: "quality"
      sort: true
      ascending: false

  # Stacked comparison showing compliant vs non-compliant
  - type: "chart"
    title: "Compliance Breakdown"
    description: "Compliant vs non-compliant percentages"
    chart:
      type: "bar_stacked_comparison"

  # Compliance matrix for these rooms
  - type: "chart"
    title: "Test Results Matrix"
    description: "Detailed test results for selected rooms"
    chart:
      type: "compliance_matrix"

  # Detailed table
  - type: "table"
    title: "Detailed Metrics"
    description: "Complete breakdown for selected rooms"

  # Recommendations
  - type: "recommendations"
    title: "Improvement Recommendations"
    description: "Actions based on performance analysis"
    max_recommendations: 10

# Output settings
output_format: ["html"]
include_interactive_charts: true
theme: "professional"

# Compliance settings
compliance_standard: "EN16798-1"
building_class: "II"
