description: Danish school CO2 guidelines
parameter: co2
filter: opening_hours
period: all_year
mode: unidirectional_ascending
threshold:
  upper: 1000
category: Danish Guidelines
building_types: [school]
room_types: [classroom, library, auditorium]
