description: Danish school temperature comfort guidelines
parameter: temperature
filter: opening_hours
period: all_year
mode: bidirectional
threshold:
  lower: 20
  upper: 26
category: Danish Guidelines
building_types: [school]  # Specifically for schools
room_types: [classroom, library, auditorium]  # Educational spaces
