description: BR18 Office - Max 25h/year >27°C (all hours during usage time)
feature: temperature
period: all_year
filter: opening_hours
mode: unidirectional_ascending
limit: 27
max_exceedance_hours: 25
regulation: BR18
building_type: office
