description: BR18 Office - Max 100h/year >26°C (all hours during usage time)
feature: temperature
period: all_year
filter: opening_hours
mode: unidirectional_ascending
limit: 26
max_exceedance_hours: 100
regulation: BR18
building_types: [office, mixed]
room_types: [office, meeting_room, classroom]  # Applicable to office-like spaces
