description: BR18 Residential - Max 100h/year >27°C (natural ventilation, all hours)
feature: temperature
period: all_year
filter: all_hours
mode: unidirectional_ascending
limit: 27
max_exceedance_hours: 100
regulation: BR18
building_types: [residential, mixed]
room_types: []  # Applies to all room types in residential buildings
ventilation_type: natural
