# Bar Chart Specific Configuration

# Figure settings
figure:
  figsize: [10, 6]
  dpi: 300

# Bar-specific settings
bars:
  width: 0.6
  alpha: 0.8
  edgecolor: black
  linewidth: 1.2

  # Bar colors for different contexts
  colors:
    default: '#3498db'
    success: '#2ecc71'
    warning: '#f39c12'
    danger: '#e74c3c'
    info: '#9b59b6'

  # Value label settings (text on top of bars)
  value_labels:
    enabled: true
    fontsize: 9
    fontweight: bold
    color: '#2c3e50'
    format: '{:.1f}%'  # Format for percentage values
    offset_factor: 0.02  # Percentage of max value for vertical offset

# Horizontal bar chart settings
horizontal:
  height: 0.6
  figsize: [8, 10]

# Grouped bar chart settings
grouped:
  bar_width_factor: 0.8  # Total width factor for group
  spacing: 0.1  # Space between bars in a group
  figsize: [12, 6]

# Stacked bar chart settings
stacked:
  alpha: 0.85
  edgecolor: white
  linewidth: 1.5

# Grid settings
grid:
  axis: y  # Only show horizontal grid lines
  alpha: 0.3
  linestyle: '--'
  linewidth: 0.8

# X-axis rotation for category labels
xaxis:
  rotation: 45
  ha: right  # horizontal alignment
  rotation_mode: anchor

# Threshold line (e.g., target/goal line)
threshold:
  enabled: true
  linewidth: 2
  linestyle: '--'
  color: '#e74c3c'
  alpha: 0.8
  label_format: 'Target: {value}%'
