# Compliance Chart Specific Configuration
# Used for gauges, compliance dashboards, priority matrices, etc.

# Figure settings
figure:
  figsize: [10, 8]
  dpi: 300

# Gauge chart settings
gauge:
  # Arc settings
  arc:
    start_angle: 180
    end_angle: 0
    linewidth: 20

  # Color thresholds for compliance levels
  color_thresholds:
    - threshold: 0
      color: '#e74c3c'  # Red (poor)
      label: 'Poor'
    - threshold: 50
      color: '#f39c12'  # Orange (fair)
      label: 'Fair'
    - threshold: 75
      color: '#f1c40f'  # Yellow (good)
      label: 'Good'
    - threshold: 90
      color: '#2ecc71'  # Green (excellent)
      label: 'Excellent'

  # Needle/pointer
  needle:
    color: '#2c3e50'
    linewidth: 3
    marker: 'v'
    markersize: 15

  # Value display
  value_display:
    fontsize: 32
    fontweight: bold
    color: '#2c3e50'
    format: '{:.1f}%'
    y_position: 0.1  # Relative position in axes

  # Labels
  threshold_labels:
    enabled: true
    fontsize: 9
    offset: 0.15

# Scatter/bubble chart for priority matrix
priority_matrix:
  figsize: [10, 10]

  # Bubble settings
  bubble:
    size_min: 100
    size_max: 2000
    alpha: 0.6
    edgecolor: black
    linewidth: 1.5

  # Quadrant lines
  quadrants:
    enabled: true
    linewidth: 1.5
    linestyle: '--'
    color: '#95a5a6'
    alpha: 0.5

    # Labels for quadrants
    labels:
      enabled: true
      fontsize: 11
      fontweight: bold
      alpha: 0.4
      positions:
        - x: 0.25
          y: 0.75
          text: 'High Impact\nLow Effort'
          color: '#2ecc71'
        - x: 0.75
          y: 0.75
          text: 'High Impact\nHigh Effort'
          color: '#f39c12'
        - x: 0.25
          y: 0.25
          text: 'Low Impact\nLow Effort'
          color: '#95a5a6'
        - x: 0.75
          y: 0.25
          text: 'Low Impact\nHigh Effort'
          color: '#e74c3c'

  # Axis settings
  axes:
    xlim: [0, 100]
    ylim: [0, 100]
    xlabel: 'Impact Score'
    ylabel: 'Effort Score'

# Compliance timeline/scatter
compliance_scatter:
  # Point settings
  marker: 'o'
  size: 50
  alpha: 0.6
  edgecolor: black
  linewidth: 0.5

  # Colors for compliance status
  colors:
    compliant: '#2ecc71'  # Green
    non_compliant: '#e74c3c'  # Red
    marginal: '#f39c12'  # Orange

  # Reference lines
  reference_lines:
    co2:
      value: 1000
      label: 'CO2 Limit (1000 ppm)'
      color: '#e74c3c'
    temperature_min:
      value: 20
      label: 'Min Temp (20°C)'
      color: '#3498db'
    temperature_max:
      value: 26
      label: 'Max Temp (26°C)'
      color: '#e74c3c'

# Stacked area for compliance over time
compliance_area:
  alpha: 0.7

  colors:
    compliant: '#2ecc71'
    non_compliant: '#e74c3c'
    no_data: '#95a5a6'

  # Boundaries
  linewidth: 1
  edgecolor: white

# Table-style compliance view
compliance_table:
  cell_colors:
    excellent: '#d5f4e6'  # Light green
    good: '#fcf3cf'  # Light yellow
    fair: '#fae5d3'  # Light orange
    poor: '#fadbd8'  # Light red

  text:
    fontsize: 10
    fontweight: normal
    align: center

  borders:
    linewidth: 1
    color: '#95a5a6'

# Legend settings (override global for compliance charts)
legend:
  fontsize: 10
  loc: upper right
  frameon: true
  framealpha: 0.9
  title: 'Compliance Status'
  title_fontsize: 11
