# Global Matplotlib Style Configuration
# This configuration applies to all graph types unless overridden

# Figure settings
figure:
  figsize: [12, 6]  # Default width, height in inches
  dpi: 300  # Resolution for saved images
  facecolor: white
  edgecolor: white
  autolayout: false

# Font settings
font:
  family: sans-serif
  sans-serif: [Arial, Helvetica, DejaVu Sans]
  size: 10
  weight: normal

# Title settings
title:
  fontsize: 16
  fontweight: bold
  color: '#2c3e50'
  pad: 15

# Axis settings
axes:
  titlesize: 14
  titleweight: bold
  titlecolor: '#2c3e50'
  labelsize: 12
  labelweight: bold
  labelcolor: '#34495e'
  edgecolor: '#95a5a6'
  linewidth: 1.2
  grid: true
  axisbelow: true
  facecolor: white
  spines:
    top: false
    right: false
    bottom: true
    left: true

# Grid settings
grid:
  alpha: 0.3
  linestyle: '--'
  linewidth: 0.8
  color: '#bdc3c7'

# Legend settings
legend:
  fontsize: 10
  frameon: true
  framealpha: 0.9
  edgecolor: '#95a5a6'
  facecolor: white
  loc: best
  shadow: false

# Line settings
lines:
  linewidth: 2
  markersize: 6
  markeredgewidth: 0.5

# Tick settings
xtick:
  labelsize: 10
  color: '#34495e'
  direction: out
  major:
    size: 5
    width: 1
  minor:
    size: 3
    width: 0.8

ytick:
  labelsize: 10
  color: '#34495e'
  direction: out
  major:
    size: 5
    width: 1
  minor:
    size: 3
    width: 0.8

# Color palette (professional color scheme)
colors:
  primary: '#3498db'      # Blue
  secondary: '#2ecc71'    # Green
  accent: '#e74c3c'       # Red
  warning: '#f39c12'      # Orange
  info: '#9b59b6'         # Purple
  neutral: '#95a5a6'      # Gray

  # Categorical palette
  categorical:
    - '#3498db'  # Blue
    - '#2ecc71'  # Green
    - '#e74c3c'  # Red
    - '#f39c12'  # Orange
    - '#9b59b6'  # Purple
    - '#1abc9c'  # Turquoise
    - '#34495e'  # Dark gray
    - '#e67e22'  # Carrot orange

  # Sequential palettes for heatmaps
  sequential:
    blue: Blues
    green: Greens
    red: Reds
    orange: Oranges
    purple: Purples

  # Diverging palettes
  diverging:
    red_blue: RdBu_r
    red_yellow_green: RdYlGn
    spectral: Spectral_r

# Threshold and reference line settings
reference_lines:
  linewidth: 2
  linestyle: '--'
  alpha: 0.7
  color: '#e74c3c'

# Target bands/zones
target_bands:
  alpha: 0.2
  color: '#d5f4e6'
  edgecolor: '#27ae60'
  linewidth: 1

# Export settings
savefig:
  dpi: 300
  format: png
  bbox_inches: tight
  pad_inches: 0.1
  facecolor: white
  edgecolor: none
