# Heatmap Specific Configuration

# Figure settings
figure:
  figsize: [12, 8]
  dpi: 300

# Heatmap cell settings
cells:
  linewidths: 0.5
  linecolor: white

# Color map settings
colormap:
  # Default colormaps for different data types
  default: YlOrRd
  temperature: RdYlBu_r
  co2: YlOrRd
  occupancy: viridis
  correlation: RdBu_r
  quality: RdYlGn

  # Normalization
  normalize: false  # Whether to normalize data to 0-1
  center: null  # Center point for diverging colormaps (null = auto)
  vmin: null  # Minimum value (null = auto)
  vmax: null  # Maximum value (null = auto)

  # Robust scaling (ignore outliers)
  robust: false
  robust_percentile: [2, 98]  # Percentiles for robust scaling

# Colorbar settings
colorbar:
  enabled: true
  location: right
  shrink: 0.8
  aspect: 20
  pad: 0.02

  label:
    text: ''
    fontsize: 11
    fontweight: bold
    rotation: 270
    labelpad: 20

  ticks:
    labelsize: 9

# Cell annotations (values displayed in cells)
annotations:
  enabled: true
  fontsize: 9
  fontweight: normal
  color: auto  # auto = black for light cells, white for dark cells
  threshold: null  # Threshold to switch text color (null = auto at 50%)
  format: '.1f'  # Number format

  # Custom formatting for specific value ranges
  custom_format:
    percentage: '{:.0f}%'
    decimal: '{:.2f}'
    integer: '{:.0f}'

# Axis labels
xaxis:
  rotation: 45
  ha: right
  fontsize: 10
  labelpad: 5

yaxis:
  rotation: 0
  ha: right
  fontsize: 10
  labelpad: 5

# Grid/mesh settings
mesh:
  edgecolors: face
  linewidth: 0

# Mask settings (for missing data)
mask:
  color: '#ecf0f1'  # Light gray for missing data
  alpha: 0.3

# Clustering/dendrograms
clustering:
  enabled: false
  method: average  # average, single, complete, ward
  metric: euclidean
  row_cluster: true
  col_cluster: true

# Special markers/overlays
markers:
  enabled: false
  symbol: 'x'
  color: black
  size: 100
  linewidth: 2
