description: Opening hours (8-15), weekdays, excludes all school holidays
hours:
  - 8
  - 9
  - 10
  - 11
  - 12
  - 13
  - 14
  - 15
weekdays_only: true
exclude_holidays: true
exclude_custom_holidays: true
