# Hotel Room Type Overrides
# Overrides building and default TAIL configuration for hotel rooms

room_type: "hotel_room"

parameter_overrides:
  # Hotel room specific noise thresholds (strictest - guest comfort priority)
  noise:
    calculation_method: "percentile"
    percentile: 5  # 5th percentile to avoid spikes
    thresholds:
      green:
        max: 25
      yellow:
        min: 25
        max: 30
      orange:
        min: 30
        max: 35
      red:
        min: 35