# Open Office Room Type Overrides
# Overrides building and default TAIL configuration for open office rooms

room_type: "open_office"

parameter_overrides:
  # Open office specific noise thresholds (less strict than small office)
  noise:
    calculation_method: "percentile"
    percentile: 5  # 5th percentile to avoid spikes
    thresholds:
      green:
        max: 35
      yellow:
        min: 35
        max: 40
      orange:
        min: 40
        max: 45
      red:
        min: 45