# Small Office Room Type Overrides
# Overrides building and default TAIL configuration for small office rooms

room_type: "small_office"

parameter_overrides:
  # Small office specific noise thresholds (stricter than open office)
  noise:
    calculation_method: "percentile"
    percentile: 5  # 5th percentile to avoid spikes
    thresholds:
      green:
        max: 30
      yellow:
        min: 30
        max: 35
      orange:
        min: 35
        max: 40
      red:
        min: 40