# EN 16798-1 Comfort Thresholds Configuration
# This YAML file defines comfort thresholds for temperature, humidity, and CO2
# for different comfort categories and room types according to EN 16798-1.

comfort_thresholds:
  temperature:
    CATEGORY_I:
      min: 21.0
      max: 23.0
    CATEGORY_II:
      min: 20.0
      max: 24.0
    CATEGORY_III:
      min: 19.0
      max: 25.0
  humidity:
    CATEGORY_I:
      min: 30.0
      max: 50.0
    CATEGORY_II:
      min: 25.0
      max: 60.0
    CATEGORY_III:
      min: 20.0
      max: 70.0
  co2:
    CATEGORY_I:
      max: 550.0
    CATEGORY_II:
      max: 800.0
    CATEGORY_III:
      max: 1200.0

room_types:
  classroom:
    description: "Standard classroom environment"
    applicable_categories: [CATEGORY_I, CATEGORY_II, CATEGORY_III]
  office:
    description: "Office workspace environment"
    applicable_categories: [CATEGORY_I, CATEGORY_II, CATEGORY_III]
  meeting_room:
    description: "Meeting or conference room"
    applicable_categories: [CATEGORY_I, CATEGORY_II, CATEGORY_III]
  gym:
    description: "Physical activity space"
    applicable_categories: [CATEGORY_II, CATEGORY_III]
  laboratory:
    description: "Lab or technical workspace"
    applicable_categories: [CATEGORY_II, CATEGORY_III]
