# IEQ Analytics Report Engine Configuration

# Report Generation Settings
report_settings:
  default_output_dir: "output/reports"
  default_charts_dir: "output/reports/charts"
  
  # Chart generation settings
  charts:
    include_by_default: true
    include_heatmaps: true
    include_time_series: true
    style: "professional"  # professional, academic, corporate
    dpi: 300
    figsize: [12, 8]
    color_palette: "Set2"
    
  # PDF generation settings
  pdf:
    page_size: "A4"  # A4, letter
    margins: [72, 72, 72, 72]  # left, right, top, bottom (points)
    include_charts: true
    style: "professional"
    
  # Data processing settings
  data_processing:
    worst_performers_count: 10
    min_data_quality_threshold: 0.8
    min_comfort_compliance_threshold: 80.0

# Worst Performer Criteria
worst_performer_criteria:
  weights:
    temperature: 0.3
    co2: 0.4
    humidity: 0.2
    data_quality: 0.1
  
  thresholds:
    min_data_quality: 0.8
    min_comfort_compliance: 80.0

# Available Report Types
report_types:
  executive_summary:
    description: "High-level overview for management"
    includes:
      - title_page
      - executive_summary
      - key_findings
      - worst_performers
      - building_overview
      - recommendations
      - key_charts
    charts:
      - worst_performers
      - performance_comparison
      - compliance_overview
      
  technical_report:
    description: "Detailed analysis for facility managers"
    includes:
      - title_page
      - methodology
      - data_quality_assessment
      - detailed_room_analysis
      - building_analysis
      - compliance_analysis
      - technical_charts
      - appendices
    charts:
      - worst_performers
      - performance_comparison
      - time_series
      - heatmaps
      - distribution_plots
      
  building_comparison:
    description: "Multi-building analysis and comparison"
    includes:
      - title_page
      - building_overview
      - performance_comparison
      - best_practices
      - resource_allocation
    charts:
      - building_comparison
      - relative_performance
      - efficiency_metrics
      
  worst_performers_focus:
    description: "Detailed analysis of problematic rooms"
    includes:
      - title_page
      - worst_performers_identification
      - root_cause_analysis
      - priority_actions
      - improvement_tracking
    charts:
      - worst_performers_detailed
      - issue_breakdown
      - trend_analysis

# Chart Types and Configurations
chart_types:
  worst_performers:
    default_type: "horizontal_bar"
    options: ["horizontal_bar", "bar_chart"]
    parameters:
      top_n: [5, 10, 15, 20]
      
  compliance_comparison:
    default_type: "grouped_bar"
    options: ["bar_chart", "horizontal_bar", "grouped_bar"]
    parameters:
      metrics: ["performance_score", "temperature_compliance", "co2_compliance", "humidity_compliance"]
      group_by: ["building", "room_type", "none"]
      
  time_series:
    default_type: "line_plot"
    options: ["line_plot", "area_plot"]
    parameters:
      parameters: ["temperature", "co2", "humidity"]
      resample_freq: ["H", "D", "W"]
      max_rooms: [5, 10, 15]
      
  heatmaps:
    default_type: "daily_hourly"
    options: ["daily_hourly", "monthly_hourly", "weekly_hourly"]
    parameters:
      parameter: ["temperature", "co2", "humidity"]
      colormap: ["RdYlBu_r", "viridis", "plasma"]
      
  distributions:
    default_type: "box_plot"
    options: ["box_plot", "violin_plot", "histogram"]
    parameters:
      parameter: ["temperature", "co2", "humidity"]
      max_rooms: [10, 20, 50]

# Interactive Configuration
interactive_options:
  enable_chart_selection: true
  enable_parameter_customization: true
  enable_filtering: true
  
  chart_menu:
    show_descriptions: true
    show_examples: true
    allow_preview: false  # Would require matplotlib backend
    
  report_customization:
    allow_section_selection: true
    allow_branding_customization: false
    allow_template_modification: false

# Performance Settings
performance:
  parallel_chart_generation: false
  max_concurrent_charts: 3
  chart_generation_timeout: 300  # seconds
  pdf_generation_timeout: 600   # seconds
  
  memory_limits:
    max_chart_data_points: 100000
    max_time_series_length: 10000
    max_heatmap_size: [365, 24]  # days x hours

# Output Settings
output:
  filename_patterns:
    executive_summary: "ieq_executive_summary_{timestamp}"
    technical_report: "ieq_technical_report_{timestamp}"
    building_comparison: "ieq_building_comparison_{timestamp}"
    worst_performers: "ieq_worst_performers_{timestamp}"
    
  chart_filename_patterns:
    worst_performers: "chart_worst_performers_{timestamp}"
    compliance_comparison: "chart_compliance_comparison_{timestamp}"
    time_series: "chart_time_series_{parameter}_{timestamp}"
    heatmap: "chart_heatmap_{parameter}_{aggregation}_{timestamp}"
    
  include_metadata: true
  generate_thumbnails: false
  compress_charts: false

# Validation Settings
validation:
  min_rooms_for_analysis: 1
  min_buildings_for_comparison: 2
  min_data_points_per_room: 100
  max_missing_data_percentage: 50
  
  chart_validation:
    min_data_points_for_chart: 10
    max_categories_in_bar_chart: 50
    min_time_series_length: 24  # hours
