description: "Temperature Category III compliance during heating season (opening hours)"
parameter: temperature
filter: opening_hours
period: heating_season
mode: bidirectional
threshold:
  lower: 19
  upper: 25
category: EN16798-1
