description: "Temperature Category III compliance during non-heating season (opening hours)"
parameter: temperature
filter: opening_hours
period: non_heating_season
mode: bidirectional
threshold:
  lower: 20
  upper: 28
category: EN16798-1
