description: "Temperature Category II compliance during non-heating season (opening hours)"
feature: temperature
filter: opening_hours
period: non_heating_season
mode: bidirectional
limits:
  lower: 22
  upper: 26
category: EN16798-1
