country: DK
custom_holidays:
  - name: Summer Holiday Start
    start_date: '2024-06-29'
    end_date: '2024-08-11'
  - name: Autumn Holiday
    start_date: '2024-10-12'
    end_date: '2024-10-20'
  - name: Christmas Holiday Start
    start_date: '2024-12-21'
    end_date: '2025-01-03'
  - name: Winter Holiday
    start_date: '2024-02-17'
    end_date: '2024-02-25'
  - name: Easter Holiday
    start_date: '2024-03-23'
    end_date: '2024-04-01'
