# Hotel Building Type Overrides
# Overrides default TAIL configuration for hotel buildings

building_type: "hotel"

parameter_overrides:
  # Hotel-specific illuminance requirements (different from office)
  illuminance:
    calculation_method: "frequency_threshold"
    threshold: 100  # Focus on minimum 100 lux
    thresholds:
      green:
        frequency_percentage: 0   # 0% time below 100 lux (100% time >= 100 lux)
      yellow:
        frequency_percentage: 50  # 0-50% time below 100 lux
      orange:
        frequency_percentage: 90  # 50-90% time below 100 lux
      red:
        frequency_percentage: 100 # >90% time below 100 lux