# Portfolio Summary Report Template
# This template generates a comprehensive portfolio-level report with key metrics,
# charts, and recommendations

template_id: portfolio_summary
name: Portfolio Summary Report
description: Executive summary report showing portfolio-wide IEQ performance, compliance rates, and recommendations
version: "1.0"
author: HVX Analytics

# Report configuration
report:
  title: "Indoor Environmental Quality - Portfolio Summary"
  subtitle: "IEQ Performance Analysis Report"
  format: html  # html or pdf
  theme: modern  # modern, classic, minimal
  scope: portfolio  # portfolio | building - determines aggregation level
  logo_path: null  # Optional path to company logo

# Page settings (for PDF)
page:
  size: A4
  orientation: portrait
  margins:
    top: 2cm
    bottom: 2cm
    left: 2cm
    right: 2cm

# Report sections
sections:
  - section_id: cover_page
    type: cover
    title: "IEQ Portfolio Analysis"
    include_date: true
    include_author: true
    custom_text: "Comprehensive Indoor Environmental Quality Assessment"

  - section_id: executive_summary
    type: summary
    title: "Executive Summary"
    content:
      - portfolio_metrics
      - key_findings
      - compliance_overview
      - critical_issues_count

  - section_id: portfolio_overview
    type: text
    title: "Portfolio Overview"
    content: |
      This report presents the analysis of indoor environmental quality (IEQ) across
      the building portfolio. The analysis covers temperature, CO2, humidity, and other
      key parameters against EN16798-1, BR18, and Danish guidelines standards.

  - section_id: compliance_charts
    type: charts
    title: "Compliance Analysis"
    layout: grid  # grid, vertical, horizontal
    charts:
      - id: compliance_overview
        title: "Overall Compliance Rates"
        width: full
        height: 400px

      - id: co2_compliance_bar
        title: "CO2 Compliance by Period"
        width: half
        height: 300px
        config:
          threshold: 1000
          show_legend: true

      - id: room_compliance_comparison
        title: "Room-Level Compliance"
        width: half
        height: 300px

  - section_id: temperature_analysis
    type: charts
    title: "Temperature Analysis"
    charts:
      - id: temperature_heatmap
        title: "Temperature Patterns (Hour × Day of Week)"
        width: full
        height: 400px
        config:
          color_scheme: RdYlBu_r

      - id: temperature_timeseries
        title: "Temperature Trends Over Time"
        width: full
        height: 300px
        config:
          moving_average: 24
          show_targets: true

  - section_id: co2_analysis
    type: charts
    title: "CO2 Analysis"
    charts:
      - id: co2_heatmap
        title: "CO2 Patterns (Hour × Day of Week)"
        width: full
        height: 400px
        config:
          color_scheme: YlOrRd
          threshold: 1000

      - id: room_temperature_co2
        title: "Temperature and CO2 Trends"
        width: full
        height: 350px

  - section_id: seasonal_patterns
    type: charts
    title: "Seasonal Performance"
    charts:
      - id: seasonal_analysis
        title: "Seasonal Variations"
        width: full
        height: 350px

      - id: daily_patterns
        title: "Daily Distribution Patterns"
        width: full
        height: 300px
        config:
          show_bounds: true

  - section_id: recommendations
    type: recommendations
    title: "Recommendations"
    max_recommendations: 10
    priority_filter: [critical, high]
    include_evidence: true
    include_weather_correlation: true

  - section_id: detailed_issues
    type: issues
    title: "Critical Issues"
    max_issues: 20
    severity_filter: [critical, high]
    group_by: building

  - section_id: summary_table
    type: table
    title: "Portfolio Summary Statistics"
    data_source: portfolio_stats
    columns:
      - Building
      - Total Rooms
      - Avg Compliance (%)
      - Critical Issues
      - Data Quality (%)

# Styling configuration
style:
  primary_color: "#2196F3"
  secondary_color: "#4CAF50"
  warning_color: "#FF9800"
  critical_color: "#F44336"
  text_color: "#333333"
  background_color: "#FFFFFF"
  font_family: "Helvetica, Arial, sans-serif"
  heading_font: "Helvetica, Arial, sans-serif"
